services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend
    restart: always
    networks:
        - app_network
    environment:
      - HTTP_SERVER_PORT=${HTTP_SERVER_PORT:-8080}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${HTTP_SERVER_PORT:-8080}/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  proxy:
    # build:
    #   dockerfile: proxy/Dockerfile
    image: nginx:alpine
    environment:
      - HTTP_SERVER_PORT=${HTTP_SERVER_PORT:-8080}
    container_name: proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./proxy/nginx.conf.template:/etc/nginx/templates/default.conf.template:ro
    depends_on:
      - backend
    networks:
      - app_network


networks:
  app_network:
    driver: bridge